var errors = {
	NONE					: {code:   0},
	NO_EMAIL				: {code:  -1, error: 'no_email'},	
	INVALID_EMAIL			: {code:  -2, error: 'invalid_email'},	
	NO_PASSWORD				: {code:  -3, error: 'no_password'},	
	NOT_SIGNED				: {code:  -4, error: 'not_signed'},	
	NO_FIRST_NAME			: {code:  -5, error: 'no_first_name'},	
	NO_LAST_NAME			: {code:  -6, error: 'no_last_name'},	
	NO_CONFIRM				: {code:  -7, error: 'no_confirm'},	
	PASSWORDS_NOT_MATCH		: {code:  -8, error: 'passwords_not_match'},
	CAN_NOT_CREATE_ACCOUNT	: {code:  -9, error: 'can_not_create_account'},
	PASSWORD_IS_TOO_SIMPLE	: {code: -10, error: 'password_is_too_simple'},
	NO_TITLE				: {code: -11, error: 'no_title'},
	NO_PRICE				: {code: -12, error: 'no_price'},
	NO_ADDRESS				: {code: -13, error: 'no_address'},
	INVALID_PRICE			: {code: -14, error: 'invalid_price'},
	NO_PHONE				: {code: -15, error: 'no_phone'},
	INVALID_PHONE			: {code: -16, error: 'invalid_phone'},
	NO_MESSAGE				: {code: -17, error: 'no_message'},
	NO_COMPANY_NAME			: {code: -18, error: 'no_company_name'},
	NO_DESCRIPTION			: {code: -19, error: 'no_description'},
	NO_RENEWDAYS			: {code: -20, error: 'no_renew_days'},
	NO_DEALTYPES			: {code: -21, error: 'no_deal_types'},
	NO_STARTDATE			: {code: -22, error: 'no_start_date'},
	NO_IMAGE				: {code: -23, error: 'image_require'},
	NO_DATE_TO				: {code: -24, error: 'date_to_require'},
	NO_DATE_FROM			: {code: -25, error: 'date_from_require'},
	DATE_EQUALS				: {code: -26, error: 'date_equals'},
	NO_NUMBER				: {code: -27, error: 'no_number'},
	NO_CURRENCY				: {code: -28, error: 'no_currency'},
	MANY_RENEW				: {code: -29, error: 'namy_renew'},
	NO_ABOUT				: {code: -30, error: 'no_about'},
	NO_WORKING_HOURS		: {code: -31, error: 'no_working_hours'},
	NO_TERMS				: {code: -32, error: 'no_terms'},
	INVALID_NUMBER			: {code: -33, error: 'invalid_number'},
	NO_ADDRESSPROFILE		: {code: -34, error: 'no_address'},
	NO_NAME					: {code: -35, error: 'no_name'},
};